"""COMP-09 — pre-installed bootable disk image output.

`iso build disk [size_gb]` packs the live chroot into a sparse qcow2
disk image that boots directly into the running OS (no installer
step).  Output: image/asgard-<ver>-amd64.qcow2.

Pipeline (all on host, under sudo):
  1. Allocate a sparse raw image of size N GB
  2. losetup -P attach → /dev/loopN with auto partition device nodes
  3. sfdisk a GPT label:
       part 1 — 1 MB unformatted with BIOS-boot type (grub i386-pc embed)
       part 2 — 100 MB vfat with ESP type (grub EFI bootloader)
       part 3 — rest, ext4 (root filesystem)
  4. mkfs.fat -F32 EFI, mkfs.ext4 -F root
  5. Mount root + EFI (under root/boot/efi)
  6. rsync -aHAX the live chroot into root
  7. Generate /etc/fstab from blkid UUIDs
  8. Bind-mount /proc /sys /dev /dev/pts into the chroot, run
     grub-install (BIOS + EFI) + update-grub via chroot
  9. Unmount everything, losetup -d
 10. qemu-img convert -O qcow2 <raw> <qcow2>; rm raw

Host prerequisites (checked at command entry):
  - rsync           (sync chroot → root partition)
  - mkfs.fat        (dosfstools package — EFI partition format)
  - qemu-img        (qemu-utils package — final raw→qcow2 conversion)
  - losetup/sfdisk/mkfs.ext4/grub-install/blkid (util-linux + grub-*)

Known v1 limitation: grub-install runs on the host, so the produced
disk image's GRUB binaries reflect the BUILD HOST'S GRUB version
(trixie 2.12 on a trixie host, etc.) — analogous to the pre-COMP-14
ISO leakage.  Follow-up will move grub-install inside the build
container (COMP-14 path-b pattern) to pin GRUB to the snapshot's
bookworm 2.06.
"""
from __future__ import annotations

import logging
import os
import subprocess
import tempfile
from typing import TYPE_CHECKING, Optional

import tui
import utils

if TYPE_CHECKING:
    from buildcontainer import BuildContainer   # noqa: F401

logger = logging.getLogger('athena.iso')


# sfdisk script that produces our 3-partition layout.  GPT label;
# part 1 = 1 MB BIOS-boot (no fs), part 2 = 100 MB ESP (vfat), part 3
# = rest = root.  Sizes are in sectors at 512 B/sector.
_SFDISK_SCRIPT_TEMPLATE = """\
label: gpt
size=2048,      type=21686148-6449-6E6F-744E-656564454649, name="BIOS-Boot"
size=204800,    type=C12A7328-F81F-11D2-BA4B-00A0C93EC93B, name="EFI", bootable
                type=0FC63DAF-8483-4772-8E79-3D69D8477DE4, name="root"
"""

# fstab template — UUIDs filled by blkid post-mkfs.  / and /boot/efi
# entries only; runtime mounts (proc, sys, run, tmp) are handled by
# systemd's defaults.
#
# fs_passno convention: only / may be 1.  The ESP gets 2 — checked
# after the root pass, never racing fsck.ext4 (the previous value 1
# ran fsck.vfat in parallel with the root check on every boot).
_FSTAB_TEMPLATE = """\
# /etc/fstab — generated by Athena Build (COMP-09 iso build disk).
# <fs spec>    <mountpoint>  <type>  <opts>          <dump> <pass>
UUID={root_uuid}  /          ext4    defaults,errors=remount-ro  0  1
UUID={efi_uuid}   /boot/efi  vfat    umask=0077                  0  2
"""


def _sudo(argv: list, password: str,
          capture: bool = True) -> subprocess.CompletedProcess:
    """sudo -S helper; mirrors iso_installer._sudo's shape."""
    return subprocess.run(
        ['sudo', '-S'] + argv,
        input=password + '\n',
        capture_output=capture, text=True,
    )


def _wait_partitions(loop_dev: str, password: str,
                     part_count: int = 3) -> bool:
    """After `losetup -P`, the kernel udev daemon creates the
    /dev/loopNp1...pN nodes asynchronously.  Wait up to 5s for them
    to appear before proceeding to mkfs.  Race observed on heavily-
    loaded build hosts."""
    import time
    _expected = [f'{loop_dev}p{i}' for i in range(1, part_count + 1)]
    for _ in range(50):
        if all(os.path.exists(_p) for _p in _expected):
            return True
        time.sleep(0.1)
    # Last resort: poke `partx -a` to force re-read.
    _sudo(['partx', '-a', loop_dev], password, capture=True)
    return all(os.path.exists(_p) for _p in _expected)


def build_disk_image(
    dir_chroot: str,
    output_qcow2: str,
    size_gb: int,
    password: str,
    container: Optional['BuildContainer'] = None,
) -> bool:
    """Build a bootable qcow2 disk image from the live chroot.

    Returns True on success, False on any error (full transcript in
    the run log; operator-facing failure messages printed via tui).

    container: accepted but unused in v1 — present so the COMP-14
    follow-up can later route grub-install through it without
    breaking the caller signature.
    """
    del container   # v1: all on host; follow-up moves grub-install in-container
    logger.info(
        f"build_disk_image: {dir_chroot} → {output_qcow2} ({size_gb}G)"
    )
    if not os.path.isdir(dir_chroot):
        tui.console.print(f"ERROR: chroot dir not found: {dir_chroot}")
        return False

    # Compose paths in the same image/ dir as the qcow2 output so
    # the raw intermediate gets cleaned up alongside.
    _img_dir = os.path.dirname(os.path.abspath(output_qcow2))
    _stem    = os.path.splitext(os.path.basename(output_qcow2))[0]
    _raw     = os.path.join(_img_dir, _stem + '.raw')
    _mnt     = os.path.join(_img_dir, _stem + '.mnt')

    # State for finally-cleanup.  None means "not yet attached/mounted".
    _loop_dev: Optional[str] = None
    _root_mounted: bool = False
    _efi_mounted: bool = False
    _bind_mounted: bool = False

    try:
        # ── Step 1: allocate sparse raw image ─────────────────────────────
        logger.info(f"step 1/8: truncate -s {size_gb}G {_raw}")
        tui.console.print(
            f"Allocating {size_gb} GB sparse raw image at {_raw}..."
        )
        _r = subprocess.run(
            ['truncate', '-s', f'{size_gb}G', _raw],
            capture_output=True, text=True,
        )
        if _r.returncode != 0:
            tui.console.print(f"ERROR: truncate failed: {_r.stderr.strip()}")
            return False

        # ── Step 2: losetup -P attach ─────────────────────────────────────
        logger.info(f"step 2/8: losetup -P {_raw}")
        _r = _sudo(['losetup', '-Pf', '--show', _raw], password)
        if _r.returncode != 0:
            tui.console.print(
                f"ERROR: losetup failed: {_r.stderr.strip()[:200]}"
            )
            return False
        _loop_dev = _r.stdout.strip()
        if not _loop_dev.startswith('/dev/loop'):
            tui.console.print(
                f"ERROR: losetup returned unexpected device "
                f"{_loop_dev!r}"
            )
            return False
        tui.console.print(f"Attached at {_loop_dev}")

        # ── Step 3: sfdisk GPT ────────────────────────────────────────────
        logger.info(f"step 3/8: sfdisk GPT layout on {_loop_dev}")
        # Write script to a tempfile + shell-redirect into sfdisk so
        # sudo's stdin gets ONLY the password and sfdisk's stdin gets
        # ONLY the script.  The combined-input approach left "label:
        # gpt" prefixed with password residue under some sudo
        # configurations (operator-observed "line 1: unsupported
        # command" 2026-05-22).
        _sf_fd, _sf_path = tempfile.mkstemp(
            prefix='sfdisk-', suffix='.script',
        )
        try:
            with os.fdopen(_sf_fd, 'w') as _fh:
                _fh.write(_SFDISK_SCRIPT_TEMPLATE)
            _r = subprocess.run(
                ['sudo', '-S', 'bash', '-c',
                 f'sfdisk --wipe always {_loop_dev} < {_sf_path}'],
                input=password + '\n',
                capture_output=True, text=True,
            )
        finally:
            try:
                os.unlink(_sf_path)
            except OSError:
                pass
        if _r.returncode != 0:
            tui.console.print(
                f"ERROR: sfdisk failed: {_r.stderr.strip()[:200]}"
            )
            return False

        # Wait for /dev/loopNp{1,2,3} to materialize
        if not _wait_partitions(_loop_dev, password):
            tui.console.print(
                f"ERROR: partition nodes did not appear under {_loop_dev}"
            )
            return False

        _bios_part = f'{_loop_dev}p1'   # not formatted, just typed
        _efi_part  = f'{_loop_dev}p2'
        _root_part = f'{_loop_dev}p3'

        # ── Step 4: mkfs ──────────────────────────────────────────────────
        logger.info(
            f"step 4/8: mkfs.fat ESP ({_efi_part}) + mkfs.ext4 root ({_root_part})"
        )
        _spin = tui.Spinner(f"mkfs.fat ESP + mkfs.ext4 root on {_loop_dev}")
        try:
            _r = _sudo(['mkfs.fat', '-F', '32', '-n', 'EFI', _efi_part],
                       password)
            if _r.returncode != 0:
                tui.console.print(
                    f"ERROR: mkfs.fat failed: {_r.stderr.strip()[:200]}"
                )
                return False
            _r = _sudo(['mkfs.ext4', '-F', '-L', 'asgard-root', _root_part],
                       password)
            if _r.returncode != 0:
                tui.console.print(
                    f"ERROR: mkfs.ext4 failed: {_r.stderr.strip()[:200]}"
                )
                return False
        finally:
            _spin.done()

        # ── Step 5: mount root, then EFI under root/boot/efi ──────────────
        logger.info(f"step 5/8: mount root + ESP under {_mnt}")
        _r = _sudo(['mkdir', '-p', _mnt], password)
        if _r.returncode != 0:
            tui.console.print(
                f"ERROR: mkdir {_mnt}: {_r.stderr.strip()[:200]}"
            )
            return False
        _r = _sudo(['mount', _root_part, _mnt], password)
        if _r.returncode != 0:
            tui.console.print(
                f"ERROR: mount root: {_r.stderr.strip()[:200]}"
            )
            return False
        _root_mounted = True
        _r = _sudo(['mkdir', '-p', os.path.join(_mnt, 'boot', 'efi')],
                   password)
        if _r.returncode != 0:
            tui.console.print(
                f"ERROR: mkdir /boot/efi: {_r.stderr.strip()[:200]}"
            )
            return False
        _r = _sudo(['mount', _efi_part,
                    os.path.join(_mnt, 'boot', 'efi')], password)
        if _r.returncode != 0:
            tui.console.print(
                f"ERROR: mount EFI: {_r.stderr.strip()[:200]}"
            )
            return False
        _efi_mounted = True

        # ── Step 6: rsync chroot → root ───────────────────────────────────
        logger.info(f"step 6/8: rsync {dir_chroot} → {_mnt}")
        _spin = tui.Spinner(
            f"rsync chroot → {_root_part} ({dir_chroot} → root partition)"
        )
        try:
            _r = _sudo(
                ['rsync', '-aHAX', '--numeric-ids',
                 '--exclude=/proc/*', '--exclude=/sys/*',
                 '--exclude=/dev/*', '--exclude=/run/*',
                 '--exclude=/tmp/*',
                 dir_chroot.rstrip('/') + '/', _mnt + '/'],
                password, capture=True,
            )
        finally:
            _spin.done()
        if _r.returncode != 0:
            tui.console.print(
                f"ERROR: rsync failed: {_r.stderr.strip()[:200]}"
            )
            return False

        # ── Step 7: fstab from blkid UUIDs ────────────────────────────────
        logger.info("step 7/8: write /etc/fstab from blkid UUIDs")
        _root_uuid = _read_uuid(_root_part, password)
        _efi_uuid  = _read_uuid(_efi_part,  password)
        if not _root_uuid or not _efi_uuid:
            tui.console.print(
                f"ERROR: blkid did not return UUIDs "
                f"(root={_root_uuid!r}, efi={_efi_uuid!r})"
            )
            return False
        _fstab = _FSTAB_TEMPLATE.format(
            root_uuid=_root_uuid, efi_uuid=_efi_uuid,
        )
        # Tempfile + sudo install pattern (same rationale as the
        # sfdisk step): keeps sudo's stdin = password only, never
        # mixed with the content we're writing.
        _fs_fd, _fs_path = tempfile.mkstemp(prefix='fstab-', suffix='.txt')
        try:
            with os.fdopen(_fs_fd, 'w') as _fh:
                _fh.write(_fstab)
            _r = _sudo(
                ['install', '-m', '644', _fs_path,
                 os.path.join(_mnt, 'etc', 'fstab')],
                password,
            )
        finally:
            try:
                os.unlink(_fs_path)
            except OSError:
                pass
        if _r.returncode != 0:
            tui.console.print(
                f"ERROR: write fstab: {_r.stderr.strip()[:200]}"
            )
            return False

        # ── Step 8: bind /proc /sys /dev /dev/pts + grub-install ──────────
        logger.info("step 8/8: bind-mount + grub-install (EFI + BIOS)")
        for _src, _sub in (
            ('/proc',    'proc'),
            ('/sys',     'sys'),
            ('/dev',     'dev'),
            ('/dev/pts', 'dev/pts'),
        ):
            _r = _sudo(['mount', '--bind', _src,
                        os.path.join(_mnt, _sub)], password)
            if _r.returncode != 0:
                tui.console.print(
                    f"ERROR: bind mount {_src}: {_r.stderr.strip()[:200]}"
                )
                return False
        _bind_mounted = True

        _spin = tui.Spinner(
            f"grub-install EFI{' + BIOS' if _has_bios_modules(_mnt) else ''} "
            f"into chroot ({_loop_dev})"
        )
        try:
            # EFI (x86_64-efi) is mandatory — every modern hypervisor /
            # cloud platform boots EFI by default.  --removable writes
            # EFI/BOOT/BOOTX64.EFI so any firmware boots it without
            # needing NVRAM entries.  --no-nvram suppresses host NVRAM
            # writes (we're building an image, not configuring the
            # host's boot order).
            #
            # Absolute path + explicit env PATH to insulate against:
            # (a) sudo configs whose secure_path doesn't include /usr/
            # sbin, and (b) the chroot's own PATH being unset.  Both
            # bit operator on first run (2026-05-22).
            _chroot_env = (
                'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:'
                '/usr/bin:/sbin:/bin'
            )
            _r = _sudo(
                ['env', _chroot_env, 'chroot', _mnt,
                 '/usr/sbin/grub-install', '--target=x86_64-efi',
                 '--efi-directory=/boot/efi', '--removable',
                 '--no-nvram'],
                password,
            )
            if _r.returncode != 0:
                tui.console.print(
                    f"ERROR: grub-install EFI: "
                    f"{_r.stderr.strip()[:200]}"
                )
                return False

            # BIOS (i386-pc) is OPPORTUNISTIC.  Skip if the chroot
            # doesn't have grub-pc-bin's modules at /usr/lib/grub/
            # i386-pc/ — operator's pkg.list may not include it
            # (config check above), or upstream resolution dropped it.
            # EFI image still boots cleanly on any UEFI firmware.
            if _has_bios_modules(_mnt):
                _r = _sudo(
                    ['env', _chroot_env, 'chroot', _mnt,
                     '/usr/sbin/grub-install', '--target=i386-pc',
                     '--boot-directory=/boot', _loop_dev],
                    password,
                )
                if _r.returncode != 0:
                    logger.warning(
                        f"grub-install BIOS returned rc={_r.returncode}: "
                        f"{_r.stderr.strip()[:200]} — EFI-only image"
                    )
                    tui.console.print(
                        "W: BIOS grub-install failed — image will be "
                        "EFI-only (UEFI hypervisors only)"
                    )
            else:
                tui.console.print(
                    "W: /usr/lib/grub/i386-pc not in chroot "
                    "(grub-pc-bin not installed) — EFI-only image"
                )

            # grub.cfg generation.  We unconditionally write a hand-
            # rolled minimal cfg instead of running `update-grub`
            # inside the chroot — update-grub is fragile under chroot
            # (depends on os-prober scanning host disks, /etc/default/
            # grub presence, the /etc/grub.d/* scripts producing a cfg
            # whose embedded paths actually work post-boot).  Operator
            # hit a grub-shell-on-boot situation 2026-05-23 where
            # update-grub appeared to succeed but produced a cfg that
            # the booted grub couldn't load.
            #
            # The minimal cfg is deterministic: one menuentry, kernel
            # found by UUID, no os-prober.  When the operator wants
            # a richer menu (multi-kernel, fallback entries), they
            # run `update-grub` post-boot from the running system —
            # at that point /etc/default/grub + os-prober work the
            # way they're designed to.
            if not _write_minimal_grub_cfg(_mnt, _root_uuid, password):
                tui.console.print(
                    "ERROR: minimal grub.cfg write failed — "
                    "image will not boot"
                )
                return False

            # ESP shim — write /boot/efi/EFI/BOOT/grub.cfg that
            # explicitly searches for the root UUID we measured
            # post-mkfs and chainloads the real cfg.
            # `grub-install --removable` embeds a prefix discovered
            # by grub-probe inside the chroot; grub-probe occasion-
            # ally guesses wrong when /boot/grub lives on a loop
            # device under a chroot bind-mount, and BOOTX64.EFI
            # then drops straight to `grub>` because its embedded
            # UUID doesn't match the actual root partition at boot
            # (operator-observed 2026-05-23).
            if not _write_efi_shim_cfg(_mnt, _root_uuid, password):
                tui.console.print(
                    "ERROR: ESP shim grub.cfg write failed — "
                    "image may not autoboot"
                )
                return False

            # Verify what actually landed on disk — the operator
            # has spent rounds debugging "did my change ship?"
            # because we previously had no signal.  Echo the first
            # lines of both cfgs + a stat of all_video.mod so the
            # log + console show ground truth.
            _verify_grub_artifacts(_mnt, password)
        finally:
            _spin.done()

        # CRITICAL: unmount + detach loop BEFORE qemu-img convert.
        # qemu-img reads the underlying raw file directly; ext4 keeps
        # writes in its page cache until umount flushes them through
        # the loop device to the raw file.  Converting while mounted
        # captures stale block data — the cfg files write OK and
        # _verify_grub_artifacts sees them on the mounted fs, but the
        # qcow2 ends up missing /boot/grub/grub.cfg and the ESP shim
        # because those writes hadn't reached the raw file yet
        # (operator-observed 2026-05-23 — grub drops to `grub>` because
        # the cfg the build wrote was never persisted to the image).
        if _bind_mounted:
            for _sub in ('dev/pts', 'dev', 'sys', 'proc'):
                _sudo(['umount', os.path.join(_mnt, _sub)],
                      password, capture=True)
            _bind_mounted = False
        if _efi_mounted:
            _r = _sudo(['umount', os.path.join(_mnt, 'boot', 'efi')],
                       password, capture=True)
            if _r.returncode != 0:
                tui.console.print(
                    f"ERROR: pre-convert umount ESP failed: "
                    f"{_r.stderr.strip()[:200]}"
                )
                return False
            _efi_mounted = False
        if _root_mounted:
            _r = _sudo(['umount', _mnt], password, capture=True)
            if _r.returncode != 0:
                tui.console.print(
                    f"ERROR: pre-convert umount root failed: "
                    f"{_r.stderr.strip()[:200]}"
                )
                return False
            _root_mounted = False
        if _loop_dev is not None:
            _sudo(['losetup', '-d', _loop_dev], password, capture=True)
            _loop_dev = None

        logger.info(f"qcow2 convert: {_raw} → {output_qcow2}")
        return _convert_to_qcow2(_raw, output_qcow2, password)

    finally:
        # Reverse-order cleanup.  Each step uses || true semantics —
        # we want to attempt ALL teardown even if one step fails (else
        # /dev/loopN stays held and the operator has to manually
        # losetup -d before retrying).  The flags above were cleared
        # on the happy path so this finally block is a no-op then;
        # on early-return failure paths the partitions are still
        # mounted and these branches actually do the teardown.
        if _bind_mounted:
            for _sub in ('dev/pts', 'dev', 'sys', 'proc'):
                _sudo(['umount', os.path.join(_mnt, _sub)],
                      password, capture=True)
        if _efi_mounted:
            _sudo(['umount', os.path.join(_mnt, 'boot', 'efi')],
                  password, capture=True)
        if _root_mounted:
            _sudo(['umount', _mnt], password, capture=True)
        if _loop_dev is not None:
            _sudo(['losetup', '-d', _loop_dev], password, capture=True)
        _sudo(['rmdir', _mnt], password, capture=True)


def _has_bios_modules(mnt: str) -> bool:
    """Check if the chroot has grub's i386-pc modules at
    /usr/lib/grub/i386-pc/.  Required for BIOS grub-install — when
    grub-pc-bin isn't installed, this dir doesn't exist and BIOS
    install fails cryptically.  Operator-observed 2026-05-22 with a
    chroot that had grub-efi-amd64-bin but not grub-pc-bin."""
    return os.path.isdir(os.path.join(mnt, 'usr', 'lib', 'grub', 'i386-pc'))


def _write_minimal_grub_cfg(mnt: str, root_uuid: str,
                              password: str) -> bool:
    """Last-resort fallback when chroot'd update-grub fails: hand-roll
    a minimal /boot/grub/grub.cfg that boots the first vmlinuz-* in
    /boot.  Single menu entry, 3-second timeout.

    Real-world cases where update-grub fails:
      - grub-mkconfig scripts can't find /etc/default/grub
      - os-prober errors out under chroot's restricted view of /dev
      - mkconfig assumes a specific filesystem layout we don't have
    """
    # Discover the kernel — version-aware, with the initrd PAIRED to the
    # chosen kernel by suffix (STA-31: the old code sorted vmlinuz and
    # initrd INDEPENDENTLY and took [-1] of each — lexicographic, so
    # 6.1.0-9 beat 6.1.0-47, and two co-resident ABIs could pair a kernel
    # with a DIFFERENT ABI's initrd → unbootable grub menuentry).
    _boot = os.path.join(mnt, 'boot')
    _pair = utils.select_latest_kernel(_boot)
    if _pair is None:
        try:
            _have_vmlinuz = any(
                _f.startswith('vmlinuz-') for _f in os.listdir(_boot))
        except OSError as e:
            logger.error(f"list {_boot} for kernel: {e}")
            return False
        if not _have_vmlinuz:
            logger.error(f"no vmlinuz-* in {_boot}")
        else:
            logger.error(
                f"no initrd.img matching the latest vmlinuz in {_boot}")
        return False
    _k_name, _i_name = _pair

    # `insmod all_video` is REQUIRED.  Without it grub's `linux`
    # command can't allocate a framebuffer for the EFI handover and
    # aborts with "no suitable video mode found", dropping the boot
    # to a grub command-line shell (operator-observed 2026-05-23 on
    # qcow2→vmdk in VMware).  all_video pulls in efi_gop, efi_uga,
    # vbe, vga as available — covers EFI + legacy BIOS.
    _cfg = (
        "# Minimal grub.cfg — generated by Asgard installer.\n"
        "# Single entry; replace via `grub-mkconfig -o /boot/grub/grub.cfg`\n"
        "# from the booted system for a fuller menu.\n"
        "set timeout=3\n"
        "set default=0\n"
        "\n"
        f"menuentry 'Asgard Linux' {{\n"
        f"    insmod all_video\n"
        f"    insmod gzio\n"
        f"    insmod part_gpt\n"
        f"    insmod ext2\n"
        f"    search --no-floppy --fs-uuid --set=root {root_uuid}\n"
        f"    linux  /boot/{_k_name} root=UUID={root_uuid} ro quiet\n"
        f"    initrd /boot/{_i_name}\n"
        f"}}\n"
    )
    _fd, _tmp = tempfile.mkstemp(prefix='grub-cfg-', suffix='.txt')
    try:
        with os.fdopen(_fd, 'w') as _fh:
            _fh.write(_cfg)
        # /boot/grub/ exists post-grub-install (EFI install creates it).
        _r = _sudo(
            ['install', '-m', '644', _tmp,
             os.path.join(mnt, 'boot', 'grub', 'grub.cfg')],
            password,
        )
    finally:
        try:
            os.unlink(_tmp)
        except OSError:
            pass
    if _r.returncode != 0:
        logger.error(
            f"install minimal grub.cfg: rc={_r.returncode}, "
            f"stderr={_r.stderr.strip()}"
        )
        return False
    return True


def _write_efi_shim_cfg(mnt: str, root_uuid: str,
                          password: str) -> bool:
    """Write /boot/efi/EFI/BOOT/grub.cfg — a tiny shim that does an
    explicit UUID search and chainloads /boot/grub/grub.cfg.

    Why: `grub-install --target=x86_64-efi --removable` writes
    BOOTX64.EFI with a prefix discovered via grub-probe.  Under
    chroot bind-mounts, grub-probe sometimes detects the wrong
    device for /boot/grub, embedding a UUID that doesn't match
    the actual root partition at boot.  Some firmware/grub
    combinations ALSO load /EFI/BOOT/grub.cfg from the ESP before
    falling back to the embedded prefix — this shim covers that
    path with the UUID we already know to be correct.
    """
    _esp_cfg_dir = os.path.join(mnt, 'boot', 'efi', 'EFI', 'BOOT')
    _r = _sudo(['mkdir', '-p', _esp_cfg_dir], password, capture=True)
    if _r.returncode != 0:
        logger.error(f"mkdir ESP shim dir: {_r.stderr.strip()}")
        return False
    _cfg = (
        "# ESP shim cfg — chains to real /boot/grub/grub.cfg via\n"
        "# explicit UUID search.  Generated by Asgard installer.\n"
        "insmod all_video\n"
        "insmod part_gpt\n"
        "insmod ext2\n"
        "insmod search_fs_uuid\n"
        f"search --no-floppy --fs-uuid --set=root {root_uuid}\n"
        "set prefix=($root)/boot/grub\n"
        "configfile ($root)/boot/grub/grub.cfg\n"
    )
    _fd, _tmp = tempfile.mkstemp(prefix='esp-shim-', suffix='.cfg')
    try:
        with os.fdopen(_fd, 'w') as _fh:
            _fh.write(_cfg)
        _r = _sudo(
            ['install', '-m', '644', _tmp,
             os.path.join(_esp_cfg_dir, 'grub.cfg')],
            password,
        )
    finally:
        try:
            os.unlink(_tmp)
        except OSError:
            pass
    if _r.returncode != 0:
        logger.error(f"install ESP shim cfg: {_r.stderr.strip()}")
        return False
    return True


def _verify_grub_artifacts(mnt: str, password: str) -> None:
    """Operator-facing proof of what landed on disk.  Reads back
    both grub.cfg files + lists /boot/grub/x86_64-efi/all_video.mod
    so the build console shows ground truth (not just our intent).

    Never fatal — purely informational.  All output goes through
    tui.console so the operator sees it during interactive runs and
    log captures it during scripted runs.
    """
    for _label, _path in (
        ('root grub.cfg',
         os.path.join(mnt, 'boot', 'grub', 'grub.cfg')),
        ('ESP shim',
         os.path.join(mnt, 'boot', 'efi', 'EFI', 'BOOT', 'grub.cfg')),
    ):
        _r = _sudo(['cat', _path], password, capture=True)
        if _r.returncode != 0:
            tui.console.print(
                f"VERIFY: {_label} MISSING at {_path} — boot will fail"
            )
            continue
        _has_video = 'insmod all_video' in _r.stdout
        _marker    = 'OK' if _has_video else 'NO all_video'
        tui.console.print(
            f"VERIFY: {_label} present ({len(_r.stdout)} bytes, "
            f"{_marker})"
        )
    # Module presence — `insmod all_video` is a no-op if the module
    # file isn't on disk for grub to load at runtime.
    _mod_path = os.path.join(
        mnt, 'boot', 'grub', 'x86_64-efi', 'all_video.mod',
    )
    _r = _sudo(['stat', '-c', '%s', _mod_path], password, capture=True)
    if _r.returncode != 0:
        tui.console.print(
            f"VERIFY: all_video.mod MISSING at {_mod_path} — "
            "grub-install didn't copy modules"
        )
    else:
        tui.console.print(
            f"VERIFY: all_video.mod present ({_r.stdout.strip()} bytes)"
        )


def _read_uuid(partition: str, password: str) -> str:
    """blkid -o value -s UUID <partition> → uuid string (empty on
    failure)."""
    _r = _sudo(
        ['blkid', '-o', 'value', '-s', 'UUID', partition],
        password, capture=True,
    )
    if _r.returncode != 0:
        logger.error(
            f"blkid {partition}: rc={_r.returncode}, "
            f"stderr={_r.stderr.strip()}"
        )
        return ''
    return _r.stdout.strip()


def _convert_to_qcow2(raw_path: str, qcow2_path: str,
                       password: str) -> bool:
    """qemu-img convert raw → qcow2 + chown to the running user +
    rm raw.  Sparse qcow2 keeps the image small (only allocated
    sectors take space)."""
    del password   # qemu-img runs as user; raw is owned via sudo so
                   # we may need sudo only for chown — see below
    _spin = tui.Spinner(
        f"qemu-img convert {os.path.basename(raw_path)} → "
        f"{os.path.basename(qcow2_path)}"
    )
    try:
        _r = subprocess.run(
            ['qemu-img', 'convert', '-O', 'qcow2', raw_path, qcow2_path],
            capture_output=True, text=True,
        )
    finally:
        _spin.done()
    if _r.returncode != 0:
        tui.console.print(
            f"ERROR: qemu-img convert failed: {_r.stderr.strip()[:200]}"
        )
        logger.error(
            f"_convert_to_qcow2: rc={_r.returncode}, stderr={_r.stderr.strip()}"
        )
        return False
    # Drop the raw intermediate (sparse but still ~size_gb apparent).
    try:
        os.unlink(raw_path)
    except OSError as e:
        logger.warning(f"unlink {raw_path}: {e}")
    _mb = os.path.getsize(qcow2_path) // (2 ** 20)
    tui.console.print(
        f"Disk image built: {qcow2_path} ({_mb} MB on disk, sparse)"
    )
    return True
