"""COMP-09 — pre-installed bootable disk image output.

`iso build disk [size_gb]` packs the live chroot into a sparse qcow2
disk image that boots directly into the running OS (no installer
step).  Output: image/asgard-<ver>-amd64.qcow2.

Pipeline (all on host, under sudo):
  1. Allocate a sparse raw image of size N GB
  2. losetup -P attach → /dev/loopN with auto partition device nodes
  3. sfdisk a GPT label:
       part 1 — 1 MB unformatted with BIOS-boot type (grub i386-pc embed)
       part 2 — 100 MB vfat with ESP type (grub EFI bootloader)
       part 3 — rest, ext4 (root filesystem)
  4. mkfs.fat -F32 EFI, mkfs.ext4 -F root
  5. Mount root + EFI (under root/boot/efi)
  6. rsync -aHAX the live chroot into root
  7. Generate /etc/fstab from blkid UUIDs
  8. Bind-mount /proc /sys /dev /dev/pts into the chroot, run
     grub-install (BIOS + EFI) + update-grub via chroot
  9. Unmount everything, losetup -d
 10. qemu-img convert -O qcow2 <raw> <qcow2>; rm raw

Host prerequisites (checked at command entry):
  - rsync           (sync chroot → root partition)
  - mkfs.fat        (dosfstools package — EFI partition format)
  - qemu-img        (qemu-utils package — final raw→qcow2 conversion)
  - losetup/sfdisk/mkfs.ext4/grub-install/blkid (util-linux + grub-*)

Known v1 limitation: grub-install runs on the host, so the produced
disk image's GRUB binaries reflect the BUILD HOST'S GRUB version
(trixie 2.12 on a trixie host, etc.) — analogous to the pre-COMP-14
ISO leakage.  Follow-up will move grub-install inside the build
container (COMP-14 path-b pattern) to pin GRUB to the snapshot's
bookworm 2.06.
"""
from __future__ import annotations

import logging
import os
import subprocess
from typing import TYPE_CHECKING, Optional

import tui

if TYPE_CHECKING:
    from buildcontainer import BuildContainer   # noqa: F401

logger = logging.getLogger('athena')


# sfdisk script that produces our 3-partition layout.  GPT label;
# part 1 = 1 MB BIOS-boot (no fs), part 2 = 100 MB ESP (vfat), part 3
# = rest = root.  Sizes are in sectors at 512 B/sector.
_SFDISK_SCRIPT_TEMPLATE = """\
label: gpt
size=2048,      type=21686148-6449-6E6F-744E-656564454649, name="BIOS-Boot"
size=204800,    type=C12A7328-F81F-11D2-BA4B-00A0C93EC93B, name="EFI", bootable
                type=0FC63DAF-8483-4772-8E79-3D69D8477DE4, name="root"
"""

# fstab template — UUIDs filled by blkid post-mkfs.  / and /boot/efi
# entries only; runtime mounts (proc, sys, run, tmp) are handled by
# systemd's defaults.
_FSTAB_TEMPLATE = """\
# /etc/fstab — generated by Athena Build (COMP-09 iso build disk).
# <fs spec>    <mountpoint>  <type>  <opts>          <dump> <pass>
UUID={root_uuid}  /          ext4    defaults,errors=remount-ro  0  1
UUID={efi_uuid}   /boot/efi  vfat    umask=0077                  0  1
"""


def _sudo(argv: list, password: str,
          capture: bool = True) -> subprocess.CompletedProcess:
    """sudo -S helper; mirrors iso_installer._sudo's shape."""
    return subprocess.run(
        ['sudo', '-S'] + argv,
        input=password + '\n',
        capture_output=capture, text=True,
    )


def _wait_partitions(loop_dev: str, password: str,
                     part_count: int = 3) -> bool:
    """After `losetup -P`, the kernel udev daemon creates the
    /dev/loopNp1...pN nodes asynchronously.  Wait up to 5s for them
    to appear before proceeding to mkfs.  Race observed on heavily-
    loaded build hosts."""
    import time
    _expected = [f'{loop_dev}p{i}' for i in range(1, part_count + 1)]
    for _ in range(50):
        if all(os.path.exists(_p) for _p in _expected):
            return True
        time.sleep(0.1)
    # Last resort: poke `partx -a` to force re-read.
    _sudo(['partx', '-a', loop_dev], password, capture=True)
    return all(os.path.exists(_p) for _p in _expected)


def build_disk_image(
    dir_chroot: str,
    output_qcow2: str,
    size_gb: int,
    password: str,
    container: Optional['BuildContainer'] = None,
) -> bool:
    """Build a bootable qcow2 disk image from the live chroot.

    Returns True on success, False on any error (full transcript in
    the run log; operator-facing failure messages printed via tui).

    container: accepted but unused in v1 — present so the COMP-14
    follow-up can later route grub-install through it without
    breaking the caller signature.
    """
    del container   # v1: all on host; follow-up moves grub-install in-container
    if not os.path.isdir(dir_chroot):
        tui.console.print(f"ERROR: chroot dir not found: {dir_chroot}")
        return False

    # Compose paths in the same image/ dir as the qcow2 output so
    # the raw intermediate gets cleaned up alongside.
    _img_dir = os.path.dirname(os.path.abspath(output_qcow2))
    _stem    = os.path.splitext(os.path.basename(output_qcow2))[0]
    _raw     = os.path.join(_img_dir, _stem + '.raw')
    _mnt     = os.path.join(_img_dir, _stem + '.mnt')

    # State for finally-cleanup.  None means "not yet attached/mounted".
    _loop_dev: Optional[str] = None
    _root_mounted: bool = False
    _efi_mounted: bool = False
    _bind_mounted: bool = False

    try:
        # ── Step 1: allocate sparse raw image ─────────────────────────────
        tui.console.print(
            f"Allocating {size_gb} GB sparse raw image at {_raw}..."
        )
        _r = subprocess.run(
            ['truncate', '-s', f'{size_gb}G', _raw],
            capture_output=True, text=True,
        )
        if _r.returncode != 0:
            tui.console.print(f"ERROR: truncate failed: {_r.stderr.strip()}")
            return False

        # ── Step 2: losetup -P attach ─────────────────────────────────────
        _r = _sudo(['losetup', '-Pf', '--show', _raw], password)
        if _r.returncode != 0:
            tui.console.print(
                f"ERROR: losetup failed: {_r.stderr.strip()[:200]}"
            )
            return False
        _loop_dev = _r.stdout.strip()
        if not _loop_dev.startswith('/dev/loop'):
            tui.console.print(
                f"ERROR: losetup returned unexpected device "
                f"{_loop_dev!r}"
            )
            return False
        tui.console.print(f"Attached at {_loop_dev}")

        # ── Step 3: sfdisk GPT ────────────────────────────────────────────
        _r = subprocess.run(
            ['sudo', '-S', 'sfdisk', '--wipe', 'always', _loop_dev],
            input=password + '\n' + _SFDISK_SCRIPT_TEMPLATE,
            capture_output=True, text=True,
        )
        if _r.returncode != 0:
            tui.console.print(
                f"ERROR: sfdisk failed: {_r.stderr.strip()[:200]}"
            )
            return False

        # Wait for /dev/loopNp{1,2,3} to materialize
        if not _wait_partitions(_loop_dev, password):
            tui.console.print(
                f"ERROR: partition nodes did not appear under {_loop_dev}"
            )
            return False

        _bios_part = f'{_loop_dev}p1'   # not formatted, just typed
        _efi_part  = f'{_loop_dev}p2'
        _root_part = f'{_loop_dev}p3'

        # ── Step 4: mkfs ──────────────────────────────────────────────────
        _spin = tui.Spinner(f"mkfs.fat ESP + mkfs.ext4 root on {_loop_dev}")
        try:
            _r = _sudo(['mkfs.fat', '-F', '32', '-n', 'EFI', _efi_part],
                       password)
            if _r.returncode != 0:
                tui.console.print(
                    f"ERROR: mkfs.fat failed: {_r.stderr.strip()[:200]}"
                )
                return False
            _r = _sudo(['mkfs.ext4', '-F', '-L', 'asgard-root', _root_part],
                       password)
            if _r.returncode != 0:
                tui.console.print(
                    f"ERROR: mkfs.ext4 failed: {_r.stderr.strip()[:200]}"
                )
                return False
        finally:
            _spin.done()

        # ── Step 5: mount root, then EFI under root/boot/efi ──────────────
        _r = _sudo(['mkdir', '-p', _mnt], password)
        if _r.returncode != 0:
            tui.console.print(
                f"ERROR: mkdir {_mnt}: {_r.stderr.strip()[:200]}"
            )
            return False
        _r = _sudo(['mount', _root_part, _mnt], password)
        if _r.returncode != 0:
            tui.console.print(
                f"ERROR: mount root: {_r.stderr.strip()[:200]}"
            )
            return False
        _root_mounted = True
        _r = _sudo(['mkdir', '-p', os.path.join(_mnt, 'boot', 'efi')],
                   password)
        if _r.returncode != 0:
            tui.console.print(
                f"ERROR: mkdir /boot/efi: {_r.stderr.strip()[:200]}"
            )
            return False
        _r = _sudo(['mount', _efi_part,
                    os.path.join(_mnt, 'boot', 'efi')], password)
        if _r.returncode != 0:
            tui.console.print(
                f"ERROR: mount EFI: {_r.stderr.strip()[:200]}"
            )
            return False
        _efi_mounted = True

        # ── Step 6: rsync chroot → root ───────────────────────────────────
        _spin = tui.Spinner(
            f"rsync chroot → {_root_part} ({dir_chroot} → root partition)"
        )
        try:
            _r = _sudo(
                ['rsync', '-aHAX', '--numeric-ids',
                 '--exclude=/proc/*', '--exclude=/sys/*',
                 '--exclude=/dev/*', '--exclude=/run/*',
                 '--exclude=/tmp/*',
                 dir_chroot.rstrip('/') + '/', _mnt + '/'],
                password, capture=True,
            )
        finally:
            _spin.done()
        if _r.returncode != 0:
            tui.console.print(
                f"ERROR: rsync failed: {_r.stderr.strip()[:200]}"
            )
            return False

        # ── Step 7: fstab from blkid UUIDs ────────────────────────────────
        _root_uuid = _read_uuid(_root_part, password)
        _efi_uuid  = _read_uuid(_efi_part,  password)
        if not _root_uuid or not _efi_uuid:
            tui.console.print(
                f"ERROR: blkid did not return UUIDs "
                f"(root={_root_uuid!r}, efi={_efi_uuid!r})"
            )
            return False
        _fstab = _FSTAB_TEMPLATE.format(
            root_uuid=_root_uuid, efi_uuid=_efi_uuid,
        )
        _r = subprocess.run(
            ['sudo', '-S', 'tee', os.path.join(_mnt, 'etc', 'fstab')],
            input=password + '\n' + _fstab,
            capture_output=True, text=True,
        )
        if _r.returncode != 0:
            tui.console.print(
                f"ERROR: write fstab: {_r.stderr.strip()[:200]}"
            )
            return False

        # ── Step 8: bind /proc /sys /dev /dev/pts + grub-install ──────────
        for _src, _sub in (
            ('/proc',    'proc'),
            ('/sys',     'sys'),
            ('/dev',     'dev'),
            ('/dev/pts', 'dev/pts'),
        ):
            _r = _sudo(['mount', '--bind', _src,
                        os.path.join(_mnt, _sub)], password)
            if _r.returncode != 0:
                tui.console.print(
                    f"ERROR: bind mount {_src}: {_r.stderr.strip()[:200]}"
                )
                return False
        _bind_mounted = True

        _spin = tui.Spinner(
            f"grub-install BIOS + EFI into chroot ({_loop_dev})"
        )
        try:
            # BIOS (i386-pc) — writes MBR + embeds core.img into part 1
            _r = _sudo(
                ['chroot', _mnt,
                 'grub-install', '--target=i386-pc',
                 '--boot-directory=/boot', _loop_dev],
                password,
            )
            if _r.returncode != 0:
                tui.console.print(
                    f"ERROR: grub-install BIOS: "
                    f"{_r.stderr.strip()[:200]}"
                )
                return False
            # EFI (x86_64-efi) — --removable writes BOOTX64.EFI so any
            # firmware boots it without NVRAM entries.
            _r = _sudo(
                ['chroot', _mnt,
                 'grub-install', '--target=x86_64-efi',
                 '--efi-directory=/boot/efi', '--removable',
                 '--no-nvram'],
                password,
            )
            if _r.returncode != 0:
                tui.console.print(
                    f"ERROR: grub-install EFI: "
                    f"{_r.stderr.strip()[:200]}"
                )
                return False
            # grub-mkconfig produces /boot/grub/grub.cfg from the
            # installed kernel(s).  Uses the chroot's /etc/default/grub
            # if any; otherwise system defaults.
            _r = _sudo(
                ['chroot', _mnt, 'update-grub'],
                password,
            )
            if _r.returncode != 0:
                # update-grub failure is a soft warning — bootloader is
                # installed; just missing the menu config.  Log and
                # continue.
                logger.warning(
                    f"update-grub returned rc={_r.returncode}: "
                    f"{_r.stderr.strip()[:200]}"
                )
        finally:
            _spin.done()

        return _convert_to_qcow2(_raw, output_qcow2, password)

    finally:
        # Reverse-order cleanup.  Each step uses || true semantics —
        # we want to attempt ALL teardown even if one step fails (else
        # /dev/loopN stays held and the operator has to manually
        # losetup -d before retrying).
        if _bind_mounted:
            for _sub in ('dev/pts', 'dev', 'sys', 'proc'):
                _sudo(['umount', os.path.join(_mnt, _sub)],
                      password, capture=True)
        if _efi_mounted:
            _sudo(['umount', os.path.join(_mnt, 'boot', 'efi')],
                  password, capture=True)
        if _root_mounted:
            _sudo(['umount', _mnt], password, capture=True)
        if _loop_dev is not None:
            _sudo(['losetup', '-d', _loop_dev], password, capture=True)
        _sudo(['rmdir', _mnt], password, capture=True)


def _read_uuid(partition: str, password: str) -> str:
    """blkid -o value -s UUID <partition> → uuid string (empty on
    failure)."""
    _r = _sudo(
        ['blkid', '-o', 'value', '-s', 'UUID', partition],
        password, capture=True,
    )
    if _r.returncode != 0:
        logger.error(
            f"blkid {partition}: rc={_r.returncode}, "
            f"stderr={_r.stderr.strip()}"
        )
        return ''
    return _r.stdout.strip()


def _convert_to_qcow2(raw_path: str, qcow2_path: str,
                       password: str) -> bool:
    """qemu-img convert raw → qcow2 + chown to the running user +
    rm raw.  Sparse qcow2 keeps the image small (only allocated
    sectors take space)."""
    del password   # qemu-img runs as user; raw is owned via sudo so
                   # we may need sudo only for chown — see below
    _spin = tui.Spinner(
        f"qemu-img convert {os.path.basename(raw_path)} → "
        f"{os.path.basename(qcow2_path)}"
    )
    try:
        _r = subprocess.run(
            ['qemu-img', 'convert', '-O', 'qcow2', raw_path, qcow2_path],
            capture_output=True, text=True,
        )
    finally:
        _spin.done()
    if _r.returncode != 0:
        tui.console.print(
            f"ERROR: qemu-img convert failed: {_r.stderr.strip()[:200]}"
        )
        logger.error(
            f"_convert_to_qcow2: rc={_r.returncode}, stderr={_r.stderr.strip()}"
        )
        return False
    # Drop the raw intermediate (sparse but still ~size_gb apparent).
    try:
        os.unlink(raw_path)
    except OSError as e:
        logger.warning(f"unlink {raw_path}: {e}")
    _mb = os.path.getsize(qcow2_path) // (2 ** 20)
    tui.console.print(
        f"Disk image built: {qcow2_path} ({_mb} MB on disk, sparse)"
    )
    return True